version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gmail_rule_engine
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: pytest tests/

volumes:
  pgdata: